server:
  port: 8083

spring:
  application:
    name: shop-order
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ShopOnline?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: your-db-password
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: your-rabbitmq-username
    password: your-rabbitmq-password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:com/shop/common/dao/*.xml
  typeAliasesPackage: com.shop.common.entity
  global-config:
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      enabled: true
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
