server:
  port: 8084

spring:
  application:
    name: shop-shopping
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 主从数据源配置
datasource:
  master:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/ShopOnline?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  slave:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/ShopOnline?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:com/shop/common/dao/*.xml
  typeAliasesPackage: com.shop.common.entity
  global-config:
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      enabled: true
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
